# Site settings
title: "SAFX Demo Generator"
destination: "../dist"
include: [
  assets/vendors/bootstrap/javascripts/bootstrap.min.js
]
exclude: [
  assets/*.scss,
  assets/**/*.scss,
  assets/components/**,
  assets/pages,
  assets/vendors/bootstrap/fonts,
  assets/vendors/bootstrap/javascripts/bootstrap/,
  assets/vendors/bootstrap/javascripts/bootstrap.js,
  assets/vendors/bootstrap/javascripts/bootstrap-sprockets.js
]

# Build settings
markdown: kramdown
